import './styles/main.css';
import { localStore } from './database/localStore.js';

const files=[['biology','Biology_Ch_1.pdf','Today, 10:30 AM','PDF'],['chem','Chemistry Notes','Today, 9:12 AM','NOTE'],['physics','Physics Formulas.pdf','Yesterday, 6:30 PM','PDF']];
const icons={home:'⌂',notes:'▧',pdf:'▱',folders:'□',star:'☆',trash:'♧',settings:'⚙',help:'?',search:'⌕'};
const app=document.querySelector('#app');
let page='landing', active='home';
function logo(){return `<div class="brand"><span class="book">▰</span>GlassNotes</div>`}
function landing(){return `<main class="landing"><nav>${logo()}<div class="navlinks"><a>Home</a><a>Features</a><a>About</a></div><div class="navactions"><button class="ghost signin">Sign in</button><button class="dark start">Get Started</button></div></nav><section class="hero"><div class="hero-copy"><h1>Your Notes.<br/>Anywhere.</h1><p>A simple, minimalist space to read PDFs, make notes and keep everything backed up securely.</p><button class="dark large start">Get Started Free <b>→</b></button><div class="benefits"><div><i>▱</i><span>Read PDFs</span></div><div><i>⌕</i><span>Take Notes</span></div><div><i>☁</i><span>Back up to Drive</span></div><div><i>▣</i><span>Access Anywhere</span></div></div></div><div class="hero-art"><div class="paper back"></div><article class="paper"><h2>Biology</h2><b>Chapter 1</b><em>The Living World</em><div class="scribble">✾</div><p>Living organisms show certain characteristics that distinguish them from non-living things.</p><hr/><hr/><hr/></article><div class="drive">▲</div><div class="notes-float"><strong>Notes</strong><span>☁</span><p>◌ &nbsp; Key points...</p><p>◌ &nbsp; Diagrams</p><p>◌ &nbsp; Important questions</p></div><div class="study">Study<br/>Smarter<br/><small>⟶</small></div></div><aside class="sign-card"><div><h2>Save. Sync. Never Lose.</h2><p>Your notes and PDFs are securely saved online and available from any device.</p><button class="google start"><b>G</b> Sign in with Google</button><small>Free&nbsp; • &nbsp;Secure&nbsp; • &nbsp;Always in your control</small></div></aside></section></main>`}
function sidebar(){const items=[['home','Home'],['notes','My Notes'],['pdf','PDF Reader'],['folders','Folders'],['star','Favorites'],['trash','Trash']];return `<aside class="sidebar">${logo()}<div class="side-menu">${items.map(([key,label])=>`<button data-page="${key}" class="${active===key?'active':''}"><i>${icons[key]}</i>${label}</button>`).join('')}</div><div class="side-bottom"><button data-page="settings"><i>⚙</i>Settings</button><button><i>◌</i>Help</button></div></aside>`}
function dashboard(){return `<div class="workspace">${sidebar()}<main class="dash"><header><div><h1>Good Afternoon, Ravi <span>👋</span></h1><p>Keep learning, keep growing.</p></div><div class="avatar">R</div></header><div class="search">${icons.search}<input placeholder="Search notes, PDFs, or folders..."/></div><section class="actions"><button data-page="pdf"><i>▱</i><b>Open PDF</b><small>Read and annotate</small></button><button data-page="notes"><i>✎</i><b>Create Note</b><small>Quick notes</small></button><button data-page="folders"><i>□</i><b>New Folder</b><small>Organize files</small></button><button data-page="settings"><i>☁</i><b>Import from Drive</b><small>Backup & restore</small></button></section><section class="recent"><div class="section-title"><h2>Recent Files</h2><button data-page="notes">View all →</button></div>${files.map(f=>`<article><i class="file ${f[0]}">${f[3]==='PDF'?'⌑':'✎'}</i><div><b>${f[1]}</b><small>${f[2]}</small></div><button>•••</button></article>`).join('')}</section></main></div>`}
function notes(){let cards=[['▧','Organic Chemistry','Important reactions...','Today, 11:00 AM'],['▧','Biology - Key Points','Chapter 1 summary...','Yesterday, 6:45 PM'],['▧','Physics Formulas','Laws of motion...','Yesterday, 4:30 PM'],['▧','Quick Revision','Important questions...','Sep 10, 2026']];return `<div class="workspace">${sidebar()}<main class="content-page"><header><h1>My Notes</h1><button class="primary new-note">＋ New Note</button></header><div class="search wide">⌕<input placeholder="Search notes..."/></div><section class="note-grid">${cards.map(c=>`<article><i>${c[0]}</i><b>${c[1]}</b><p>${c[2]}</p><small>${c[3]}</small><button>⋮</button></article>`).join('')}</section></main></div>`}
function folders(){return `<div class="workspace">${sidebar()}<main class="content-page"><header><h1>Folders</h1><button class="primary">＋ New Folder</button></header><section class="folder-list">${[['🟩','Biology','12 files'],['🟦','Chemistry','8 files'],['🟨','Physics','10 files'],['🟥','Important','5 files']].map(f=>`<article><i>${f[0]}</i><div><b>${f[1]}</b><small>${f[2]}</small></div><button>•••</button></article>`).join('')}</section></main></div>`}
function pdf(){return `<div class="workspace">${sidebar()}<main class="reader"><header><button>←</button><b>Biology_Ch_1.pdf</b><span></span><button>⇩</button><button>⛶</button><div class="avatar">R</div></header><div class="reader-body"><aside class="thumbnails"><p>Pages</p><div class="thumb selected">1<br/><small>Chapter 1</small></div><div class="thumb">2</div><div class="thumb">3</div></aside><section class="document"><div class="pdf-tools">‹ &nbsp; 1 / 24 <span>− &nbsp; <b>100%</b> &nbsp;＋</span></div><article class="pdf-page"><small>CHAPTER 01</small><h1><em>1</em> The Living World</h1><h4>CHAPTER</h4><h2>1.1 &nbsp; What's ‘Living’?</h2><p>Living organisms show certain characteristics that distinguish them from non-living things.</p><ul><li>Growth</li><li>Reproduction</li><li>Metabolism</li><li>Response to stimuli</li><li>Adaptation</li></ul><div class="plant">🌿</div></article></section><aside class="reading-notes"><div><b>Notes</b><span>Bookmarks</span></div><textarea placeholder="Write your notes here..."></textarea><footer><button><b>B</b></button><button><i>I</i></button><button>U</button><span></span><button class="primary">Save Note</button></footer></aside></div></main></div>`}
function settings(){return `<div class="workspace">${sidebar()}<main class="content-page settings"><header><h1>Settings</h1></header><section class="backup"><h2>Google Drive Backup</h2><p>Keep your notes and PDFs safe with Google Drive.</p><article><i class="drive-small">▲</i><div><b>Connected</b><small>ravi.patel@example.com</small></div><button>Disconnect</button></article><label><span>Auto backup <small>Automatically save changes to Google Drive</small></span><input type="checkbox" checked/></label><label><span>Sync on startup <small>Sync files when you open the app</small></span><input type="checkbox" checked/></label><footer><button class="primary">Back up now</button><button>Restore from Drive</button><span>● Last backup: Today, 11:42 AM</span></footer></section></main></div>`}
function render(){app.innerHTML=page==='landing'?landing():page==='home'?dashboard():page==='notes'?notes():page==='folders'?folders():page==='pdf'?pdf():settings();bind();}
function bind(){document.querySelectorAll('.start,.signin').forEach(b=>b.onclick=()=>{page='home';active='home';render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;active=page;render()});document.querySelector('.new-note')?.addEventListener('click',()=>{const title=prompt('Name your note','Untitled note');if(title) localStore.saveNote({title,content:'',updatedAt:Date.now()});});}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js'));
render();
